apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: test-app
profiles:
- name: prd
  manifests:
    rawYaml:
    - service-prd.yaml
- name: stg
  manifests:
    rawYaml:
    - service-stg.yaml
deploy:
  cloudrun: {}
verify:
- name: verify
  container:
    name: verify
    image: ubuntu
    command:
    - echo
    - ok
