apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-app-stg
spec:
  template:
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: run-sa # from-param: ${run_sa}
      containers:
      - image: app
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
